### ISSUE TITLE
Using mongo-relation with separate model files?

### ISSUE THREAD

**Issue by ghost** [jcspencer/mongo-relation#6]
I'm trying to use mongo-relation with models that are in separate files.

in foo.js:

```
var mongoose = require('mongoose'),
  Schema = mongoose.Schema,
  Bar = require('./bar');
require('mongo-relation');

var FooSchema = new Schema({
  bar: Schema.Types.ObjectId
});

FooSchema.hasOne('Bar', { through: 'bar' });
module.exports = mongoose.model('Foo', FooSchema);
```

and bar.js:

```
var mongoose = require('mongoose'),
  Schema = mongoose.Schema;
require('mongo-relation');

var BarSchema = new Schema({
  stuff: String
});
// no belongsTo, as a Bar can be in a Foo, but also in a Baz and a Quux
module.exports = mongoose.model('Bar', BarSchema);
```

In some other file, I `var Foo = require('foo.js');` and then try:

```
var foo = new Foo();
foo.bar.stuff = 'Lorem ipsum';
```

Then I get the error message "Cannot set property 'stuff' of undefined". Clearly, I'm supposed to require Bar in some way, but I don't really understand where. Your examples have all the models in the same file, but that's not an option for this project, as we have way too many models.

Thanks for any help, and kind regards,

André Fischer

P.S. Yes, I'm a bit new to Node and Mongoose...

**Comment by jcspencer** [comment]
As far as I can see, there are two issues I can see:

The first is that you are requiring `foo.js` instead of `./foo.js`, which is loading it from the `node_modules` folder.

The second is that you are never initialising foo.bar. I've included an example reference.

``` javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;

mongoose.connect('mongodb://localhost/test'); //connect to mongo
require('mongo-relation'); //add relations

// Create a Foo
var FooSchema = new Schema({
    bars: [mongoose.Schema.ObjectId]
  });
FooSchema.hasMany('Bar', {dependent: 'delete', through: 'bars'});
var Foo = mongoose.model('Foo', FooSchema);

// Create a Bar
var BarSchema = new Schema({
    stuff: String,
    owner: {type: ObjectId, ref: 'Foo'}
  });
BarSchema.belongsTo('Foo', {through: 'owner'});
var Bar = mongoose.model('Bar', BarSchema);

// Use them
var aFoo = new Foo();
aFoo.bars.create({stuff: "mongo is cool, yo"}, function(err, foo, bar) {
    if(err) throw err;
    aFoo.bars.create({stuff: "mongo is the coolest, yo"}, function(err, foo, bar) {
        if(err) throw err;
        foo.bars.find({}, console.log.bind(console)); //output all of the Bars in aFoo
    });
});
```

And as far as I know, you cannot have model relationships between more than two models types (Bar can belong to a Foo, but not a Foo and Baz) as of _yet_, I plan to add this feature soon :smile:

Hope this helps

**Comment by ghost** [comment]
My bad, in the example, I should have said that I _do_ indeed `require('./foo.js');`

am I correct, then, in the model file foo.js to require('bar'), and that I _must_ add a belongsTo() in bar.js as well for it to work? As it stands, calling foo.bar.create() fails with a similar error as when I try to set foo.bar.stuff...
