### ISSUE TITLE
Association Implementation

### ISSUE THREAD

**Issue by jonstorer** [jcspencer/mongo-relation#7]
James,

I'd like to discuss the implementation of `hasMany`. Is there a way to implement the `hasMany` association without creating an array of ids on the document that owns the `hasMany` relationship?

Imagine a situation where `UserSchema.hasMany('Alert')` and `AlertSchema.belongsTo('User')`. When a `user` has 5 `alerts` the association stands up. The user model will hold 5 alerts ids in an array on the user model. Great.

However, when that same users has 20000 alerts, the user model will end up with an array of 20000 ids. That doesn't seem maintainable.

Also, let's say I have an endpoint to retrieve a user's alerts `created_at` after `someDate`. When I query my alerts, I'll be searching with 20000 ids even though I might only find 1 document.

Is there a way to implement the `hasMany` relationship by only adding the `user._id` to the `alert` model?

**Comment by jcspencer** [comment]
If I'm interpreting correctly, and you want to store the `user._id` with the `alert` model (as usual), but don't want to store the alerts id's with the user who owns them.

As it stands, each Alert in MongoDB will contain the `user` field, which is a MongoDB ObjectID that points to the Alert's owner. Therefore, you could query the Alert model like so:

``` javascript
Alert.where('user._id').equals(mongoose.Schema.ObjectId("theobjectidgoeshere"))
       .exec(callback); 
// find alerts owned by the user
```

And get a User, minus the array of ObjectIDs:

``` javascript
User.find({ _id: mongoose.Schema.ObjectId("theobjectidgoeshere") })
       .select('-alerts')
       .exec(callback); 
// get a user, minus the alert objectid array
```

If you'd like, I could add an option to not save ObjectIDs into the primary object?

(edit: correct fields/queries)

**Comment by jcspencer** [comment]
(Please note that even though the above code doesn't return the array of alert ObjectIDs, they still exist in MongoDB, and are just not being sent with the query response)

**Comment by jcspencer** [comment]
Also, in the instance of having huge amounts of alerts, I would recommend using Mongoose's QueryStream, which streams documents from the database instead of pulling an array. This can be used like so:

``` javascript
var stream = Alert.where('user._id').equals(mongoose.Schema.ObjectId("theobjectidgoeshere")).stream();

stream.on('data', function (doc) {
  // do something with the mongoose document
}).on('error', function (err) {
  // handle the error
}).on('close', function () {
  // the stream is closed
});
```

A QuerySteam can also be piped through/into transform/writeable/duplex streams, just like any node.js readable stream.

Using streams allows you to process documents in async, without having to have the entire query response from mongoose before manipulating/viewing the response.

**Comment by jonstorer** [comment]
James,

Typically we won't be pulling all alerts at once. The many thousands of alerts situation is an issue when users have used the system for a while. 

Our situation is more of a paginated resource in an API. We need to pull a user's alerts in groups of N. My concern with the module's hasMany implementation is that as the relationship grows, the number of ids being sent in the query to mongo grows as well. If the query were restructured to look for a foriegn key in the other collection, the query size is constant no matter the number of associated documents. 

Thanks for the streaming tip, when we start pushing tons of data I'll give it a try. 
—
Jonathon

**Comment by jcspencer** [comment]
Like I stated earlier, the only thing the query needs to search for is alerts where the contained ObjectId referring to the owner is equal to the user.

So if I wanted all the Alerts owned by a User with the ObjectId "hereisanobjectid", I could do this:

``` javascript
Alert.where('user._id').equals(mongoose.Schema.ObjectId("hereisanobjectid"));
```

And in terms of pagination, I would recommend using the brilliant plugin [mongoose-pagination](https://github.com/moveline/mongoose-pagination) by moveline. It simply adds the ability to call `.paginate(from, to)` on a query. Like so:

``` javascript
Alert.where('user._id').equals(mongoose.Schema.ObjectId("hereisanobjectid")).paginate(0, 10).exec(cb); // get alerts 0..10 from the user

Alert.where('user._id').equals(mongoose.Schema.ObjectId("hereisanobjectid")).paginate(11, 20).exec(cb); // get alerts 11..20 from the user
```

**Comment by jonstorer** [comment]
James,

Thanks for the feed back. I do understand how relationships work, but thanks for the review. My reason for bringing this up on this module is that I would like to add the functionality. It's convenient to be able to use `user.alerts.create({})` to build new objects.

I'd love your feedback on whether you'd be interested is moving this module in that direction.

Jon

**Comment by jcspencer** [comment]
Building new objects with `.create()` is available [here](https://github.com/JamesS237/mongo-relation/blob/master/lib/relationships.js#L160), and can be used with a single object, or an array. Like so:

``` javascript
user.posts.create({
  title: "Mongoose, now with added love through relationships!"
}, function(err, user, post){
  // user.posts.length === 1
  // post.title === "Mongoose, now with added love through relationships!"
});

// Using an `Array`
user.posts.create([
    { title: "Not too imaginative post title" }
  , { title: "... a tad more imaginative post title" }
], function(err, user, posts){
  // user.posts.length === 3
  // posts.length == 2
  // posts[0] instanceof Post
});
```

**Comment by jcspencer** [comment]
Note, this is only available on Mongoose Arrays, so you cannot use `.create()` with `hasOne`

**Comment by jonstorer** [comment]
James,

I understand. I'd like to figure out a way to make that happen. 

I believe it can be done with mongoose's virtuals. 
—
Jonathon
